#!/bin/sh
pip install schematics
pip install pathlib
pip install humanize
sudo add-apt-repository "deb https://apt.ebaker.me.uk/ubuntu/ trusty main"
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 7D4367B0
